name: Docker Image CI

on:
  push:
    branches:
      - master
      - '*/docker/**'
  pull_request:
    branches:
      - '*/docker/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker-compose --file docker-compose.linux.yml build
